language: ruby
script: rspec
before_install:
  - 'test "$CQL_ENABLE_AUTH" = "1" && sudo perl -pi -e "s/(?<=authenticator: )AllowAllAuthenticator/PasswordAuthenticator/" /usr/local/cassandra/conf/cassandra.yaml && echo "Authentication enabled" || echo "Authentication disabled"'
  - 'test "$CQL_ENABLE_AUTH" = "1" && sudo service cassandra restart || :'
env:
  global:
    - CQL_ENABLE_AUTH=0
services:
  - cassandra
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby
  - jruby-head
  - rbx-2
jdk:
  - openjdk7
matrix:
  include:
    - rvm: 2.1.1
      env: CQL_ENABLE_AUTH=1
      jdk: openjdk7
    - rvm: jruby
      jdk: oraclejdk8
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
